project_id = "akqkqzdoatqfpbtejeyt"

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.setup-push]
verify_jwt = false

[functions.send-push-notifications]
verify_jwt = false
